# verify-fix-f7-87-89-93-99.ps1  (regression for the four dev-module P2 fixes)
#
# F7-87 dev_project.code used to be generated by COUNT(*)+1: deleting any row makes the next number
#        fall back into the range that is still in use (min_id=10 proves rows were deleted), and two
#        concurrent submits get the same count. idx_code was a plain index, so the DB did not stop it.
#        Fix: take MAX(code)+1 (same shape as BugController.generateBugCode) + UNIQUE KEY uk_code.
# F7-89 updateProject wrote the WHOLE @RequestBody entity, so the edit page echoed a stale `status`
#        back over the value derived from project phases. Combined with a leftover cancelled_at the
#        project could never be closed (silent deadlock), because syncProjectStatus short-circuited on
#        cancelledAt while the phase guard judged by status. Fix: whitelist update + one single
#        criterion (status) + frontend stops sending status.
# F7-93 duplicate phase-template names made checkProductStatusSync's selectOne hit 2 rows ->
#        TooManyResultsException -> complete/skip/save-phase returned 500 for every project.
#        Fix: uniqueness check on create/update + LIMIT 1 fallback + UNIQUE KEY uk_company_name.
# F7-99 screen_model is an industry-wide shared knowledge base, but it was tenant-filtered, so the
#        2336 seed rows (all company_id=1) were invisible to companies 2/3. Fix: IGNORE_TABLES +
#        company_id normalised to NULL + entity no longer auto-fills it.
#
# All assertions are read-only (SELECT / information_schema / source regex). No row is written.
# ASCII-only on purpose (PS 5.1 + BOM pitfalls).

$ErrorActionPreference = 'Continue'
$MYSQL  = 'E:\dev\mysql\mysql-8.0.46-winx64\bin\mysql.exe'
$SERVER = 'c:\Users\75629\CodeBuddy\20260710123705\beichen-erp\beichen-erp-server\src\main\java\com\beichen\erp'
$WEB    = 'c:\Users\75629\CodeBuddy\20260710123705\beichen-erp\beichen-erp-web\src'
$env:MYSQL_PWD = 'root'
$script:fails = 0

function Sql([string]$sql) {
  $out = & $MYSQL --default-character-set=utf8mb4 -uroot -D beichen_erp -N -B -e $sql 2>&1
  return ($out | Out-String).Trim()
}
function SqlOne([string]$sql) { $v = Sql $sql; if ($v -eq '') { return '' }; return ($v -split "`n")[0].Trim() }
function Ok([string]$m)   { Write-Output ("  [OK]   " + $m) }
function Bad([string]$m)  { Write-Output ("  [FAIL] " + $m); $script:fails++ }
function Info([string]$m) { Write-Output ("  [INFO] " + $m) }
function Has([string]$path, [string]$pattern) {
  if (-not (Test-Path $path)) { return $false }
  return ((Get-Content $path -Raw -Encoding UTF8) -match $pattern)
}
function IndexExists([string]$table, [string]$index) {
  return [int](SqlOne "SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA='beichen_erp' AND TABLE_NAME='$table' AND INDEX_NAME='$index' AND NON_UNIQUE=0")
}

# ================= F7-87: project code generation =================
Write-Output '=== F7-87: dev_project code generation + UNIQUE KEY ==='

if ((IndexExists 'dev_project' 'uk_code') -ge 1) { Ok "dev_project.code carries a UNIQUE key (uk_code)" }
else { Bad "dev_project.code has no UNIQUE key -- duplicate project codes can still be persisted" }

$projSvc = "$SERVER\dev\service\impl\ProjectServiceImpl.java"
if (Has $projSvc 'orderByDesc\(Project::getCode\)') { Ok "generateProjectCode orders by code DESC (MAX(code)+1)" }
else { Bad "generateProjectCode no longer orders by code DESC" }
if (Has $projSvc 'last\("LIMIT 1"\)') { Ok "generateProjectCode uses LIMIT 1 to read the last code" }
else { Bad "generateProjectCode does not use LIMIT 1" }
if (Has $projSvc 'selectCount\(w\)') { Bad "the old COUNT(*)+1 code path is still present" }
else { Ok "the old COUNT(*)+1 code path is gone" }

# quantitative check: simulate "one row deleted" and show the old algorithm collides with a live code
$projCount = [int](SqlOne "SELECT COUNT(*) FROM dev_project")
if ($projCount -ge 2) {
  $minId     = SqlOne "SELECT MIN(id) FROM dev_project"
  $dayPrefix = SqlOne "SELECT SUBSTRING_INDEX(MAX(code),'-',2) FROM dev_project"
  $oldNext   = SqlOne "SELECT LPAD(COUNT(*)+1,3,'0') FROM dev_project WHERE id <> $minId AND code LIKE '$dayPrefix-%'"
  $newNext   = SqlOne "SELECT LPAD(CAST(SUBSTRING_INDEX(MAX(code),'-',-1) AS UNSIGNED)+1,3,'0') FROM dev_project WHERE id <> $minId AND code LIKE '$dayPrefix-%'"
  $collide   = SqlOne "SELECT code FROM dev_project WHERE id <> $minId AND code = '$dayPrefix-$oldNext'"
  if ($collide -ne '') {
    Ok "old algorithm collides after one delete: its next number '$dayPrefix-$oldNext' is already used by '$collide'"
  } else {
    Info "old algorithm next='$dayPrefix-$oldNext' happens to be free in the current dataset (new algorithm next='$dayPrefix-$newNext')"
  }
  if ($oldNext -ne $newNext) { Ok "old vs new numbering differ after one delete (old=$oldNext new=$newNext)" }
  else { Info "old and new numbering agree on the current dataset (old=$oldNext new=$newNext)" }
} else {
  Info "less than 2 projects present; the after-delete simulation is skipped"
}

# ================= F7-89: project status not overridable =================
Write-Output '=== F7-89: project status cannot be overwritten by the edit page ==='

# NOTE: scope the check to the updateProject body. Searching the whole file for /updateById\(project\)/
# would also hit cancel() -- which legitimately writes status+cancelledAt -- and the javadoc that
# documents the old behaviour; both produced false FAILs before this was scoped.
$updateBlock = [regex]::Match((Get-Content $projSvc -Raw -Encoding UTF8),
  'public void updateProject\(Project project\) \{([\s\S]*?)\n    \}').Groups[1].Value
if ($updateBlock -eq '') { Bad "could not locate the updateProject body" }
elseif ($updateBlock -match 'updateById\(project\)') { Bad "updateProject still writes the whole request entity" }
else { Ok "updateProject no longer writes the whole request entity" }
if (Has $projSvc 'Project patch = new Project\(\)') { Ok "updateProject builds a whitelist patch entity" }
else { Bad "updateProject whitelist patch entity is missing" }

$patchBlock = [regex]::Match((Get-Content $projSvc -Raw -Encoding UTF8),
  'Project patch = new Project\(\);([\s\S]*?)projectMapper\.updateById\(patch\)').Groups[1].Value
if ($patchBlock -eq '') { Bad "could not locate the whitelist patch block" }
else {
  foreach ($forbidden in @('setStatus\(', 'setCancelledAt\(', 'setCode\(', 'setProductId\(', 'setCompanyId\(', 'setActualEndDate\(')) {
    if ($patchBlock -match $forbidden) { Bad ("whitelist patch still writes " + $forbidden) }
    else { Ok ("whitelist patch does not write " + $forbidden) }
  }
}

$phaseSvc = "$SERVER\dev\service\impl\ProjectPhaseServiceImpl.java"
if (Has $phaseSvc 'getCancelledAt\(\) != null\)\s*return') { Bad "syncProjectStatus still short-circuits on cancelledAt (deadlock path)" }
else { Ok "syncProjectStatus no longer short-circuits on cancelledAt" }
if (Has $phaseSvc 'ProjectStatus\.CANCELLED\.getCode\(\)\.equals\(project\.getStatus\(\)\)') {
  Ok "syncProjectStatus uses the same criterion as the phase guard (status)"
} else { Bad "syncProjectStatus does not use the status criterion" }

$dtoSrc = Get-Content "$WEB\api\system.ts" -Raw -Encoding UTF8
$dtoBlock = [regex]::Match($dtoSrc, 'export interface ProjectDTO \{([\s\S]*?)\r?\n\}').Groups[1].Value
if ($dtoBlock -eq '') { Bad "could not locate ProjectDTO in api/system.ts" }
# NOTE: only match a real field declaration line; the DTO carries a comment mentioning "status".
elseif ($dtoBlock -match '(?m)^\s*status\?') { Bad "ProjectDTO still declares status (edit page can submit it)" }
else { Ok "ProjectDTO no longer carries status" }

$editVue = Get-Content "$WEB\views\dev\project\edit.vue" -Raw -Encoding UTF8
if ($editVue -match 'status:\s*p\.status') { Bad "edit.vue still echoes status from the detail response" }
else { Ok "edit.vue no longer echoes status" }
# NOTE: negative lookbehind -- /form\.status/ would also match `bugForm.status` (the bug dialog),
# which is unrelated to the project form.
if ($editVue -match '(?<!bug)form\.status') { Bad "edit.vue still references form.status" }
else { Ok "edit.vue does not reference form.status" }

# ================= F7-93: duplicate phase-template names =================
Write-Output '=== F7-93: phase template uniqueness + selectOne fallback ==='

if ((IndexExists 'dev_phase_template' 'uk_company_name') -ge 1) { Ok "dev_phase_template has UNIQUE KEY uk_company_name(company_id,name)" }
else { Bad "dev_phase_template has no unique key on (company_id,name)" }

$dupTpl = [int](SqlOne "SELECT COUNT(*) FROM (SELECT company_id,name FROM dev_phase_template GROUP BY company_id,name HAVING COUNT(*)>1) t")
if ($dupTpl -eq 0) { Ok "no duplicate phase-template names exist right now" }
else { Bad "$dupTpl duplicate phase-template name(s) exist -- complete/skip phase would have 500'd" }

$tplSvc = "$SERVER\dev\service\impl\PhaseTemplateServiceImpl.java"
if (Has $tplSvc 'selectCount\(buildWrapper\(\)') { Ok "PhaseTemplateServiceImpl validates duplicate names on create/update" }
else { Bad "PhaseTemplateServiceImpl has no duplicate-name validation" }
if (Has $tplSvc 'ne\(PhaseTemplate::getId') { Ok "the update path excludes its own id when checking duplicates" }
else { Bad "the update path does not exclude its own id" }
if (Has $phaseSvc 'orderByAsc\(PhaseTemplate::getId\)') { Ok "checkProductStatusSync falls back to ordering + LIMIT 1" }
else { Bad "checkProductStatusSync still uses a bare selectOne" }
# NOTE: match the signature, not the comment that documents the removal.
if (Has $phaseSvc 'public void updateStatus\(') { Bad "the dead updateStatus method is still present" }
else { Ok "the dead updateStatus method has been removed" }

# ================= F7-99: screen_model is a shared knowledge base =================
Write-Output '=== F7-99: screen_model shared across companies ==='

if (Has "$SERVER\config\CompanyTenantHandler.java" '"screen_model"') { Ok "screen_model is registered in IGNORE_TABLES" }
else { Bad "screen_model is not in IGNORE_TABLES (tenant filter still applies)" }

$entSrc = Get-Content "$SERVER\dev\entity\ScreenModel.java" -Raw -Encoding UTF8
if ($entSrc -match 'FieldFill\.INSERT\)\s*private Long companyId') { Bad "ScreenModel.companyId is still auto-filled on insert" }
else { Ok "ScreenModel.companyId is no longer auto-filled" }

$rows  = [int](SqlOne "SELECT COUNT(*) FROM screen_model")
$nulls = [int](SqlOne "SELECT COUNT(*) FROM screen_model WHERE company_id IS NULL")
if ($rows -gt 0 -and $rows -eq $nulls) { Ok "all $rows knowledge-base rows are shared (company_id IS NULL)" }
else { Bad "expected every row to be shared, got NULL rows = $nulls / $rows" }

$distinctCo = [int](SqlOne "SELECT COUNT(DISTINCT company_id) FROM screen_model WHERE company_id IS NOT NULL")
if ($distinctCo -eq 0) { Ok "no row is bound to a single company any more" }
else { Bad "$distinctCo company-specific bucket(s) remain in screen_model" }

if (Has "$SERVER\config\DataInitializer.java" 'UPDATE screen_model SET company_id = NULL') {
  Ok "DataInitializer normalises company_id on first import (old seed sql stays compatible)"
} else { Bad "DataInitializer does not normalise company_id after the seed import" }

# ================= summary =================
Write-Output ''
if ($script:fails -eq 0) { Write-Output 'ALL CHECKS PASSED' }
else { Write-Output ("FAILED CHECKS: " + $script:fails); exit 1 }
