package com.beichen.erp.finance.task;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.beichen.erp.config.CompanyContext;
import com.beichen.erp.finance.service.FinanceBillService;
import com.beichen.erp.system.entity.Company;
import com.beichen.erp.system.mapper.CompanyMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.time.LocalDate;
import java.util.List;

/**
 * 账单自动生成定时任务（方案A：到期即出账）。
 * <p>每天凌晨 2 点检查各公司：客户/供应商存在「到期（dueDate ≤ 今天）未结清」的应收/应付，
 * 且未被未作废账单覆盖时，自动生成一张<b>草稿</b>账单（人工审核后才生效，与手动生成一致）。</p>
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class FinanceBillAutoTask {

    private final CompanyMapper companyMapper;
    private final FinanceBillService billService;

    /** 每天凌晨 2 点执行 */
    @Scheduled(cron = "0 0 2 * * ?")
    public void autoGenerateDaily() {
        run(LocalDate.now());
    }

    /**
     * 执行一轮自动账单生成（定时任务与手动触发接口共用）。
     * <p>定时线程无登录态：{@code CompanyContext} 为空时租户插件放行全表、companyId 字段填充为空，
     * 因此必须<b>逐公司</b>设置上下文，保证应收/应付查询按公司隔离、finance_bill.company_id 正确落库。</p>
     *
     * @return 执行结果摘要（供手动触发接口返回）
     */
    public String run(LocalDate today) {
        // sys_company 不参与租户隔离，可跨公司查询；status=1 为启用
        List<Company> companies = companyMapper.selectList(new LambdaQueryWrapper<Company>().eq(Company::getStatus, 1));
        int total = 0;
        StringBuilder summary = new StringBuilder();
        for (Company c : companies) {
            try {
                CompanyContext.set(c.getId());
                List<FinanceBillService.AutoBillCommand> plan = billService.autoGeneratePlan(today);
                int ok = 0;
                // 逐条独立事务执行：单张账单失败不影响其它
                for (FinanceBillService.AutoBillCommand cmd : plan) {
                    try {
                        billService.generate(cmd.billType(), cmd.partnerId(), cmd.partnerName(), cmd.periodStart(), cmd.periodEnd());
                        ok++;
                    } catch (Exception ex) {
                        log.error("自动账单生成失败 company={} billType={} partnerId={}", c.getId(), cmd.billType(), cmd.partnerId(), ex);
                    }
                }
                total += ok;
                summary.append("公司[").append(c.getCompanyName()).append("] 计划 ").append(plan.size())
                        .append(" 张、成功 ").append(ok).append(" 张；");
            } catch (Exception ex) {
                log.error("自动账单任务公司处理失败 company={}", c.getId(), ex);
                summary.append("公司[").append(c.getCompanyName()).append("] 失败：").append(ex.getMessage()).append("；");
            } finally {
                CompanyContext.clear();
            }
        }
        String result = "自动账单完成：共生成 " + total + " 张。" + summary;
        log.info(result);
        return result;
    }
}
