package com.beichen.erp.finance.task;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.beichen.erp.config.CompanyContext;
import com.beichen.erp.finance.service.FinanceBillService;
import com.beichen.erp.system.entity.Company;
import com.beichen.erp.system.mapper.CompanyMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.List;

/**
 * 账单自动生成定时任务（方案A：到期即出账）。
 * <p>每天凌晨 2 点检查各公司：客户/供应商存在「到期（dueDate ≤ 今天）未结清」的应收/应付，
 * 且未被未作废账单覆盖时，自动生成一张<b>草稿</b>账单（人工审核后才生效，与手动生成一致）。</p>
 *
 * <p><b>P0 多实例安全（2026-09-14）</b>：定时任务默认在所有实例上都会触发，多实例部署会重复生成草案。
 * 这里加两层保护：① {@code app.scheduling.enabled=false} 可整体排除本 Bean（生产多实例建议只开一个）；
 * ② 任务入口用 MySQL 命名锁 {@code GET_LOCK} 抢占"本轮执行权"（连接断开/进程崩溃自动释放，无需新表、无需 Redis）。</p>
 */
@Slf4j
@Component
@RequiredArgsConstructor
@ConditionalOnProperty(name = "app.scheduling.enabled", havingValue = "true", matchIfMissing = true)
public class FinanceBillAutoTask {

    /** 跨实例互斥锁名（MySQL GET_LOCK，全程 ≤64 字符） */
    private static final String LOCK_NAME = "beichen:finance-bill-auto";

    private final CompanyMapper companyMapper;
    private final FinanceBillService billService;
    private final DataSource dataSource;

    /** 每天凌晨 2 点执行（带跨实例互斥，见 {@link #runScheduled}） */
    @Scheduled(cron = "0 0 2 * * ?")
    public void autoGenerateDaily() {
        runScheduled(LocalDate.now());
    }

    /**
     * 定时入口：先用 MySQL 命名锁抢占本轮执行权，抢不到即跳过（其他实例正在执行）。
     * <p>锁绑在本次取得的连接上，方法返回即 {@code RELEASE_LOCK}；进程异常退出时连接关闭、
     * MySQL 也会自动释放，因此不会出现"锁泄漏导致任务永久不跑"。</p>
     */
    public void runScheduled(LocalDate today) {
        try (Connection conn = dataSource.getConnection()) {
            Integer acquired = queryInt(conn, "SELECT GET_LOCK('" + LOCK_NAME + "', 0)");
            if (acquired == null || acquired != 1) {
                log.info("自动账单任务：未抢到实例锁（其他实例执行中），本轮跳过");
                return;
            }
            try {
                run(today);
            } finally {
                queryInt(conn, "SELECT RELEASE_LOCK('" + LOCK_NAME + "')");
            }
        } catch (Exception e) {
            log.error("自动账单任务获取实例锁失败，本轮跳过", e);
        }
    }

    /** 执行单值查询（GET_LOCK / RELEASE_LOCK；NULL 归一为 0，便于判等） */
    private Integer queryInt(Connection conn, String sql) {
        try (Statement st = conn.createStatement(); ResultSet rs = st.executeQuery(sql)) {
            return rs.next() ? rs.getInt(1) : null;
        } catch (Exception e) {
            log.error("执行锁语句失败 sql={}", sql, e);
            return null;
        }
    }

    /**
     * 执行一轮自动账单生成（定时任务与手动触发接口共用）。
     * <p>定时线程无登录态：{@code CompanyContext} 为空时租户插件放行全表、companyId 字段填充为空，
     * 因此必须<b>逐公司</b>设置上下文，保证应收/应付查询按公司隔离、finance_bill.company_id 正确落库。</p>
     *
     * @return 执行结果摘要（供手动触发接口返回）
     */
    public String run(LocalDate today) {
        // sys_company 不参与租户隔离，可跨公司查询；status=1 为启用
        List<Company> companies = companyMapper.selectList(new LambdaQueryWrapper<Company>().eq(Company::getStatus, 1));
        int total = 0;
        StringBuilder summary = new StringBuilder();
        for (Company c : companies) {
            try {
                CompanyContext.set(c.getId());
                List<FinanceBillService.AutoBillCommand> plan = billService.autoGeneratePlan(today);
                int ok = 0;
                // 逐条独立事务执行：单张账单失败不影响其它
                for (FinanceBillService.AutoBillCommand cmd : plan) {
                    try {
                        billService.generate(cmd.billType(), cmd.partnerId(), cmd.partnerName(), cmd.periodStart(), cmd.periodEnd());
                        ok++;
                    } catch (Exception ex) {
                        log.error("自动账单生成失败 company={} billType={} partnerId={}", c.getId(), cmd.billType(), cmd.partnerId(), ex);
                    }
                }
                total += ok;
                summary.append("公司[").append(c.getCompanyName()).append("] 计划 ").append(plan.size())
                        .append(" 张、成功 ").append(ok).append(" 张；");
            } catch (Exception ex) {
                log.error("自动账单任务公司处理失败 company={}", c.getId(), ex);
                summary.append("公司[").append(c.getCompanyName()).append("] 失败：").append(ex.getMessage()).append("；");
            } finally {
                CompanyContext.clear();
            }
        }
        String result = "自动账单完成：共生成 " + total + " 张。" + summary;
        log.info(result);
        return result;
    }
}
