package com.beichen.erp.finance.task;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.beichen.erp.config.CompanyContext;
import com.beichen.erp.exception.BusinessException;
import com.beichen.erp.finance.service.FinanceBillService;
import com.beichen.erp.system.entity.Company;
import com.beichen.erp.system.mapper.CompanyMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.List;

/**
 * 账单自动生成定时任务（方案A：到期即出账）。
 * <p>每天凌晨 2 点检查各公司：客户/供应商存在「到期（dueDate ≤ 今天）未结清」的应收/应付，
 * 且未被未作废账单覆盖时，自动生成一张<b>草稿</b>账单（人工审核后才生效，与手动生成一致）。</p>
 *
 * <p><b>P0 多实例安全（2026-09-14）</b>：定时任务默认在所有实例上都会触发，多实例部署会重复生成草案。
 * 这里加两层保护：① {@code app.scheduling.enabled=false} 可整体排除本 Bean（生产多实例建议只开一个）；
 * ② 任务入口用 MySQL 命名锁 {@code GET_LOCK} 抢占"本轮执行权"（连接断开/进程崩溃自动释放，无需新表、无需 Redis）。</p>
 */
@Slf4j
@Component
@RequiredArgsConstructor
@ConditionalOnProperty(name = "app.scheduling.enabled", havingValue = "true", matchIfMissing = true)
public class FinanceBillAutoTask {

    /** 跨实例互斥锁名（MySQL GET_LOCK，全程 ≤64 字符） */
    private static final String LOCK_NAME = "beichen:finance-bill-auto";

    private final CompanyMapper companyMapper;
    private final FinanceBillService billService;
    private final DataSource dataSource;

    /** 每天凌晨 2 点执行（带跨实例互斥，见 {@link #runScheduled}） */
    @Scheduled(cron = "0 0 2 * * ?")
    public void autoGenerateDaily() {
        runScheduled(LocalDate.now());
    }

    /**
     * 定时入口：先用 MySQL 命名锁抢占本轮执行权，抢不到即跳过（其他实例正在执行）。
     * <p>锁绑在本次取得的连接上，方法返回即 {@code RELEASE_LOCK}；进程异常退出时连接关闭、
     * MySQL 也会自动释放，因此不会出现"锁泄漏导致任务永久不跑"。</p>
     */
    public void runScheduled(LocalDate today) {
        try (Connection conn = dataSource.getConnection()) {
            Integer acquired = queryInt(conn, "SELECT GET_LOCK('" + LOCK_NAME + "', 0)");
            if (acquired == null || acquired != 1) {
                log.info("自动账单任务：未抢到实例锁（其他实例执行中），本轮跳过");
                return;
            }
            try {
                run(today);
            } finally {
                queryInt(conn, "SELECT RELEASE_LOCK('" + LOCK_NAME + "')");
            }
        } catch (Exception e) {
            log.error("自动账单任务获取实例锁失败，本轮跳过", e);
        }
    }

    /** 执行单值查询（GET_LOCK / RELEASE_LOCK；NULL 归一为 0，便于判等） */
    private Integer queryInt(Connection conn, String sql) {
        try (Statement st = conn.createStatement(); ResultSet rs = st.executeQuery(sql)) {
            return rs.next() ? rs.getInt(1) : null;
        } catch (Exception e) {
            log.error("执行锁语句失败 sql={}", sql, e);
            return null;
        }
    }

    /**
     * 执行一轮自动账单生成（**定时任务专用**：遍历全部启用公司）。
     * <p>定时线程无登录态：{@code CompanyContext} 为空时租户插件放行全表、companyId 字段填充为空，
     * 因此必须<b>逐公司</b>设置上下文，保证应收/应付查询按公司隔离、finance_bill.company_id 正确落库。</p>
     *
     * @return 执行结果摘要
     */
    public String run(LocalDate today) {
        // sys_company 不参与租户隔离，可跨公司查询；status=1 为启用
        List<Company> companies = companyMapper.selectList(new LambdaQueryWrapper<Company>().eq(Company::getStatus, 1));
        StringBuilder summary = new StringBuilder();
        int total = runFor(companies, today, summary);
        String result = "自动账单完成：共生成 " + total + " 张。" + summary;
        log.info(result);
        return result;
    }

    /**
     * F7-38（2026-09-19）：只跑**指定公司**（手动触发接口用）。
     *
     * <p>手动入口原先直接调用 {@link #run(LocalDate)} ⇒ 任何持有 {@code finance:bill} 页面码的用户
     * 都能触发**跨公司**批量出账。现收口为"手动只跑当前公司"，跨租户全量只留给平台超管显式触发
     * （见 {@code FinanceBillController#autoGenerate}）。</p>
     */
    public String runForCompany(Long companyId, LocalDate today) {
        if (companyId == null) throw new BusinessException("当前公司上下文缺失，无法生成账单");
        Company c = companyMapper.selectById(companyId);
        if (c == null) throw new BusinessException("公司不存在：" + companyId);
        if (!Integer.valueOf(1).equals(c.getStatus())) throw new BusinessException("公司已停用，无法生成账单");
        StringBuilder summary = new StringBuilder();
        int total = runFor(List.of(c), today, summary);
        String result = "自动账单完成：共生成 " + total + " 张。" + summary;
        log.info(result);
        return result;
    }

    /**
     * F7-39#8（2026-09-19）：**手动入口也抢同一把跨实例锁** —— 原先只有定时入口 {@link #runScheduled} 加锁，
     * 手动 {@code /auto-generate} 完全绕过 {@code GET_LOCK}（只靠 JVM 内 {@code synchronized} + 账期查重兜底）
     * ⇒ 多实例部署时两个实例同时点"立即执行"仍可重复出账。
     *
     * <p>与定时入口的差别：抢不到锁**不静默跳过**，而是明确报错（手动操作需要即时反馈）。等待 5 秒
     * （定时入口用 0 秒不等待，抢不到就下一轮）。</p>
     */
    public String runAllLocked(LocalDate today) {
        return withLock(() -> run(today));
    }

    /** F7-39#8：手动"只跑当前公司"入口的加锁版本（见 {@link #runAllLocked}） */
    public String runForCompanyLocked(Long companyId, LocalDate today) {
        return withLock(() -> runForCompany(companyId, today));
    }

    /** 在跨实例命名锁内执行一轮（锁绑在本次连接上，方法返回即释放；进程异常退出由 MySQL 自动释放） */
    private String withLock(java.util.function.Supplier<String> body) {
        try (Connection conn = dataSource.getConnection()) {
            Integer acquired = queryInt(conn, "SELECT GET_LOCK('" + LOCK_NAME + "', 5)");
            if (acquired == null || acquired != 1)
                throw new BusinessException("账单生成正在执行中（其他实例或请求持有锁），请稍后重试");
            try {
                return body.get();
            } finally {
                queryInt(conn, "SELECT RELEASE_LOCK('" + LOCK_NAME + "')");
            }
        } catch (BusinessException be) {
            throw be;
        } catch (Exception e) {
            log.error("账单生成获取实例锁失败", e);
            throw new BusinessException("账单生成锁获取失败：" + e.getMessage());
        }
    }

    /** 逐公司生成一轮（定时任务传全部启用公司；手动入口只传当前公司），返回成功张数 */
    private int runFor(List<Company> companies, LocalDate today, StringBuilder summary) {
        int total = 0;
        for (Company c : companies) {
            try {
                CompanyContext.set(c.getId());
                List<FinanceBillService.AutoBillCommand> plan = billService.autoGeneratePlan(today);
                int ok = 0;
                // 逐条独立事务执行：单张账单失败不影响其它
                for (FinanceBillService.AutoBillCommand cmd : plan) {
                    try {
                        billService.generate(cmd.billType(), cmd.partnerId(), cmd.partnerName(), cmd.periodStart(), cmd.periodEnd());
                        ok++;
                    } catch (Exception ex) {
                        log.error("自动账单生成失败 company={} billType={} partnerId={}", c.getId(), cmd.billType(), cmd.partnerId(), ex);
                    }
                }
                total += ok;
                summary.append("公司[").append(c.getCompanyName()).append("] 计划 ").append(plan.size())
                        .append(" 张、成功 ").append(ok).append(" 张；");
            } catch (Exception ex) {
                log.error("自动账单任务公司处理失败 company={}", c.getId(), ex);
                summary.append("公司[").append(c.getCompanyName()).append("] 失败：").append(ex.getMessage()).append("；");
            } finally {
                CompanyContext.clear();
            }
        }
        return total;
    }
}
